package com.example.bookshopapp.data;

import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

import javax.persistence.*;
import java.util.List;

@Entity @Table(name = "authors") @Getter @Setter @Accessors(chain = true)
public class Author {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("author id is generated by db")
    private Integer id;
    private String firstName;
    private String lastName;
    @OneToMany(mappedBy = "author")
    private List<Book> bookList;

    public Author() { }


    public Author(Integer id, String firstName, String lastName) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
    }
}
